openapi: 3.0.3
info:
  title: geo-tiler
  description: geo-tiler
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  '/ping':
    get:
      tags:
        - Health
      responses:
        200:
          description: pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
  '/tilingJob':
    post:
      description: creates a zone tiling job
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ZoneTilingJob"
      responses:
        200:
          description: the created zone tiling job
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ZoneTilingJob"
components:
  schemas:
    Geometry:
      type: object
      properties:
        id:
          type: string
    ZoneTilingJob:
      type: object
      properties:
        id:
          type: string
        geometries:
          type: array
          items:
            $ref: "#/components/schemas/ZoneTilingJob"